### PR TITLE
Change esprima link in dependency

### PR DESCRIPTION
**Pull request by tahmidshahriar**
To fix this issue (in CodeCombat):

https://github.com/codecombat/codecombat/issues/2853

### CODE REVIEW

**Comment by tahmidshahriar** [comment]
I am not fully sure why the build failed with the only change being in dependency and the installation appears to be working fine. I would greatly appreciate any advice on how to fix this! :)

**Comment by tahmidshahriar** [comment]
One of the reasons the tests might be failing might be because this downloads from a different branch. Initially, it was downloading from harmony branch. Recently, that branch had everything other than the main code removed from its branch and thus it no longer had scripts such as esparse.js which it needed to run. So, if I try to use the harmony branch, I get the enoent error. The change I made causes it to download from the master branch and that might be the reason the tests are failing.

<b> Error : </b>
image

**Comment by tahmidshahriar** [comment]
This is no longer valid as ariya updated his branch and added the tools in bin, so the harmony branch should work once again.

**Comment by nwinter** [comment]
Ah, that makes it easy.

Looks like we should be updating to the latest Esprima 2.x instead; that probably is going to be faster and work better than the old harmony branch. Just need to update to it and test everything to see if there have been any incompatible changes.

**Pull request closed without merging**
